kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: use-ecr-image
    image: eoin-test:latest
    commands:
      - echo "Running commands inside the ECR image"
