kind: pipeline
name: default
type: docker

steps:
  - name: publish
    image: plugins/docker
    pull: always
    settings:
      tag: latest
      repo: eoinmcafee/eoin-test
      username:
        from_secret: username
      password:
        from_secret: password


