kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: hello
    image: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test:latest
    pull_policy: always
    commands:
    - echo hello there from ecr
