kind: pipeline
name: default

steps:
  - name: ecr-login
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      aws_session_token:
        from_secret: aws_session_token
      region: us-east-2
      repo: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test
