kind: pipeline
name: default
type: docker

steps:
  - name: use-ecr-image
    image: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test
    commands:
      - echo "Running commands inside the ECR image"
