kind: pipeline
type: aws
name: default

pool:
  use: osx-anka

steps:
  - name: check install
    commands:
      - hostname -f
      - ifconfig
      - touch /tmp/blaaaa
      - env
      - whoami
      - echo $PATH
      - echo $0
      - cat $0
