kind: pipeline
name: default
type: docker

steps:
  - name: push-to-gar
    image: plugins/gcr
    pull: never
    settings:
      tag: latest
      repo: eoin-test
      registry_type: GAR
      gar_location: us
      project_id: ci-play
      json_key:
        from_secret: gcr_json_key
