kind: pipeline
type: vm
name: default

pool:
  use: anka-build

steps:
  - name: check xcode versions
    commands:
      - echo $PATH
      - sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/Contents/Developer
      - xcodebuild -version
      - sudo xcode-select -switch /Application/Xcode-14.1.0.app
      - xcodebuild -version
      - sudo xcode-select -switch /Application/xcode-14.0.0.app
