kind: pipeline
name: default
type: docker

steps:
  - name: push-to-gar
    image: plugins/gcr
    pull: never
    settings:
      tag: latest
      repo: ci-play/eoin-test/test
      registry_type: GCR
      location: us
      oidc_token:
        from_secret: token