kind: pipeline
type: vm
name: default

pool:
  use: anka-build

steps:
  - name: check xcode versions
    commands:
      - sudo xcode-select -switch /Applications/Xcode-14.1.0.app
      - xcodebuild -version
      - sudo xcode-select -switch /Applications/Xcode-14.1.0.app
