kind: pipeline
name: default

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: Username  
      password:
        from_secret: Password  
      region: us-east-2
      repo: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test
