kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: hello
    image: 392115778539.dkr.ecr.us-east-2.amazonaws.com/myalpine:latest
    commands:
    - echo hello there from ecr
