kind: pipeline
name: default

steps:
  - name: use-ecr-image
    image: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test
    commands:
      - echo "Running commands inside the ECR image"

image_pull_secrets:
  - ecr_credentials
