kind: pipeline
name: default
type: docker

steps:
    - name: scan
      image: eoinmcafee00/drone-container-scanner
      pull: if-not-exists
      settings:
          log_level: debug
          scan_uri: http://ea3c144c953d.ngrok.io
          image_name: ubuntu:14.04
          fail_level: high