kind: pipeline
type: aws
name: default

pool:
  use: ubuntu-xenial

steps:
  - name: check install
    commands:
      - hostname -f
      - ifconfig
      - touch /tmp/blaaaa
      - env
      - whoami