kind: pipeline
name: default
type: docker

steps:
  - name: create-s3-bucket
    image: plugins/aws-cli
    pull: always
    settings:
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      aws_region: us-east-2
      aws_session_token:
        from_secret: aws_session_token
      commands:
        - aws s3api create-bucket --bucket my-test-bucket-12345 --region us-east-2