kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    pull: if-not-exists
    commands:
      - dotnet build
  - name: scan
    pull: never
    image: drone-plugins/drone-snyk
    privileged: true
    settings:
      repo: eoinmcafee/drone-test
      dockerfile: RunHelloWorld/Dockerfile
      image: mcr.microsoft.com/dotnet/sdk:5.0
      debug: true
      username:
        from_secret: username
      password:
        from_secret: password
      snyk_token:
        from_secret: snyk
      fail_error_on_step: false