kind: pipeline
name: default
type: vm

pool:
  use: ubuntu

platform:
  os: linux
  arch: amd64

steps:
  - name: push-to-gar
    image: eoinmcafee/kaniko-gar
    pull: always
    settings:
      tag: latest
      repo: ci-play/eoin-test/test
      location: europe
      project_number: 763860969292
      pool_id: drone
      provider_id: local
      service_account_email: harness-ci-automation@ci-play.iam.gserviceaccount.com
      oidc_token_id:
        from_secret: token