kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    pull: if-not-exists
    commands:
      - dotnet build

  - name: docker
    pull: if-not-exists
    image: docker-local
    settings:
      repo: eoinmcafee/drone-test
      dockerfile: RunHelloWorld/Dockerfile
      dry_run: true