kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: use-ecr-image
    image: 093396591680.dkr.ecr.us-east-2.amazonaws.com/eoin-test:latest
    commands:
      - echo "Running commands inside the ECR image"
